DROP TABLE basketball_games;

CREATE TABLE basketball_games (
			id INT,
			date VARCHAR(100),
			time VARCHAR(100),
            timestamp INT,
            timezone VARCHAR(100),
            stage VARCHAR(100),
            week VARCHAR(100),
            status_long VARCHAR(100),
            status_short VARCHAR(100),
            status_timer VARCHAR(100),
            league_id INT,
            league_name VARCHAR(100),
            league_type VARCHAR(100),
            league_season VARCHAR(100),
            league_logo VARCHAR(100),
            country_id INT,
            country_name VARCHAR(100),
            country_code VARCHAR(100),
            country_flag VARCHAR(100),
            teams_home_id INT,
            teams_home_name VARCHAR(100),
            teams_home_logo VARCHAR(100),
            teams_away_id INT,
            teams_away_name VARCHAR(100),
            teams_away_logo VARCHAR(100),
            scores_home_quarter_1 NUMERIC,
            scores_home_quarter_2 NUMERIC,
            scores_home_quarter_3 NUMERIC,
            scores_home_quarter_4 NUMERIC,
            scores_home_over_time NUMERIC,
            scores_home_total NUMERIC,
            scores_away_quarter_1 NUMERIC,
            scores_away_quarter_2 NUMERIC,
            scores_away_quarter_3 NUMERIC,
            scores_away_quarter_4 NUMERIC,
            scores_away_over_time NUMERIC,
            scores_away_total NUMERIC
			)
